## Prevendo se uma pessoa pode ter uma doença cardíaca ou não

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# importando o DataFrame

df = pd.read_csv('heart.csv')

In [3]:
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

## Tratamento e transformação dos Dados

In [4]:
# excluindo colunas indesejáveis

df = df.drop('Unnamed: 0', axis=1)

In [5]:
df.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [6]:
# verificando o tipo dos dados

df.dtypes

Age            int64
Sex            int64
ChestPain     object
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal          object
AHD           object
dtype: object

In [7]:
# Neste caso a Variável "ChestPain" e a variável "Thal" são multiclasse

# vou aplicar uma codificação : LabelEncoder

from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()

In [8]:
# copiar o data Frame

df_enc = df
df_enc.head(2)

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes

In [9]:
# aplicando a codificação nas variáveis desejadas

df_enc['ChestPain'] = le.fit_transform(df_enc['ChestPain'])

In [10]:
df_enc.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,normal,No

In [11]:
# aplicando a codificação na variável "Thal"

df_enc['Thal'] = le.fit_transform(df_enc['Thal'])

TypeError: argument must be a string or number

In [12]:
# Para codificar, a variável Thal deve ser do tipo string ou número, mas ela está em object

# Convertendo o formato da variável para string

df_enc['Thal'] = df_enc['Thal'].astype(str)

In [13]:
# Aplicando a codificação da variável novamente

df_enc['Thal'] = le.fit_transform(df_enc['Thal'])

In [14]:
df_enc.head()

,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,63,1,3,145,233,1,2,150,0,2.3,3,0.0,0,No
1,67,1,0,160,286,0,2,108,1,1.5,2,3.0,2,Yes
2,67,1,0,120,229,0,2,129,1,2.6,2,2.0,3,Yes
3,37,1,1,130,250,0,0,187,0,3.5,3,0.0,2,No
4,41,0,2,130,204,0,2,172,0,1.4,1,0.0,2,No

In [15]:
df_enc.dtypes

Age            int64
Sex            int64
ChestPain      int32
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal           int32
AHD           object
dtype: object

In [16]:
# As variáveis ChestPain e Thal estão em formato diferente das outras inteiras

# É preciso transformar para int64

from numpy import int64

In [17]:
df_enc['ChestPain'] = df_enc['ChestPain'].astype(int64)
df_enc['Thal'] = df_enc['Thal'].astype(int64)

In [18]:
df_enc.dtypes

Age            int64
Sex            int64
ChestPain      int64
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal           int64
AHD           object
dtype: object

In [19]:
# Convertendo a variável alvo - (Target) para 0 ou 1 (Classificação binária)

# Onde for Sim: 1, Onde for não: 0

map_apply = {'Yes' : 1, 'No' : 0}

df_enc['AHD'] = df_enc['AHD'].map(map_apply)

In [20]:
df_enc['AHD'].head()

0    0
1    1
2    1
3    0
4    0
Name: AHD, dtype: int64

In [21]:
# Verificando se os formatos estão OK

df_enc.dtypes

Age            int64
Sex            int64
ChestPain      int64
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal           int64
AHD            int64
dtype: object

In [22]:
# Uma Vez que os dados estão formatados, vou verificar se existe nulos (Missing Values)

df_enc.isnull().values.any()

True

In [23]:
# Existem Missing Values!

# Verificando em qual colunas eles estão

for column in df_enc.columns:
    if df_enc[column].isnull().values.any():
        print('Missing Values em: {0}'.format(str(column)))

Missing Values em: Ca

In [24]:
# Existem Missing values somente em Ca

# Verificando o tipo dos dados da coluna
df_enc['Ca'].head()

0    0.0
1    3.0
2    2.0
3    0.0
4    0.0
Name: Ca, dtype: float64

In [25]:
# Tratando Missing Values e transformando para 0.0

df_enc['Ca'] = df_enc['Ca'].fillna(0.0)

In [26]:
# Verificando o resultado: Se existem nulos no dataFrame

df_enc.isnull().values.any()

False

In [27]:
df_enc.dtypes

Age            int64
Sex            int64
ChestPain      int64
RestBP         int64
Chol           int64
Fbs            int64
RestECG        int64
MaxHR          int64
ExAng          int64
Oldpeak      float64
Slope          int64
Ca           float64
Thal           int64
AHD            int64
dtype: object

## Dividindo os dados em Teste e Treinamento

In [28]:
# Definindo as variáveis de entrada - Features e a variável Target

X = df_enc.drop('AHD', axis=1).values

y = df_enc['AHD'].values

In [29]:
# Dividindo os dados utilizando cross Validation

from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score

# dividindo os dados em folds

kfold = KFold(n_splits=10, shuffle=True, random_state=7)

## Escolha e treinamento do modelo

In [30]:
# Como trata-se de um problema de classificação
# Vou utilizar LogisticRegression, SVM e Kneighbors(KNN)
# Esses modelos precisam de normalização ou de padronização

from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.neighbors import KNeighborsClassifier

lor_model = LogisticRegression()
svm_model = SVC()
knn_model = KNeighborsClassifier()

## Testando os modelos com padronização

In [31]:
# importando StandardScaler e padronizando os dados

from sklearn.preprocessing import StandardScaler

In [32]:
scaler = StandardScaler()
scale = scaler.fit(X)
X = scale.transform(X)

In [33]:
# Resultado Logistic Regression

lor_result = cross_val_score(lor_model, X, y, cv= kfold)

print('Acurácia: {0:.2f}%'.format(lor_result.mean() * 100))

Acurácia: 81.86%

In [34]:
# Resultado Suport Vector Machine

svm_result = cross_val_score(svm_model, X, y, cv= kfold)

print('Acurácia: {0:.2f}%'.format(svm_result.mean() * 100))

Acurácia: 80.87%

In [35]:
# Resultado KNN

knn_result = cross_val_score(knn_model, X, y, cv=kfold)

print('Acurácia: {0:.2f}%'.format(knn_result.mean() * 100))

Acurácia: 80.55%

## Testando os modelos com Normalização

In [36]:
# importando MinMaxScaler

from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
scale = scaler.fit(X)
X = scale.transform(X)

In [37]:
# Resultado Logistic Regression

lor_result = cross_val_score(lor_model, X, y, cv= kfold)

print('Acurácia: {0:.2f}%'.format(lor_result.mean() * 100))

Acurácia: 82.20%

In [38]:
# Resultado Suport Vector Machine

svm_result = cross_val_score(svm_model, X, y, cv= kfold)

print('Acurácia: {0:.2f}%'.format(svm_result.mean() * 100))

Acurácia: 82.19%

In [39]:
# Resultado KNN

knn_result = cross_val_score(knn_model, X, y, cv=kfold)

print('Acurácia: {0:.2f}%'.format(knn_result.mean() * 100))

Acurácia: 80.86%

### Neste caso a Normalização gerou um resultado melhor em relação á Padronização
### E o modelo final escolhido foi o LogisticRegression

In [41]:
# Savando do modelo

import joblib

joblib.dump(lor_model, 'LogisticRegression.sav')

['LogisticRegression.sav']

In [42]:
# Carregando o modelo

loaded_model = joblib.load('LogisticRegression.sav')

In [44]:
# Fazendo previsões como o modelo carregado

loaded_model.fit(X, y.ravel())

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [48]:
pred = loaded_model.predict([[52, 0, 3, 145, 233, 1, 2, 109, 0, 2.3, 3, 0.0, 0]])
pred

array([1], dtype=int64)